# Generated by Django 4.2 on 2026-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_brand_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('brand_logo', models.URLField(blank=True, null=True)),
                ('brand_website', models.URLField(blank=True, null=True)),
                ('brand_address', models.TextField(blank=True, null=True)),
                ('is_brand_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_brand_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
