# Generated by Django 4.2 on 2026-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_brand_id_alter_customuser_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
    ]
