# Generated by Django 4.2 on 2026-04-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslpayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_payment', to='users.order'),
        ),
    ]
